// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkDgUn8hvTooqzNfeQauGnafNez-it638',
    appId: '1:338772583049:android:3cbde9210d886c507a1c58',
    messagingSenderId: '338772583049',
    projectId: 'aids-feedback-app',
    storageBucket: 'aids-feedback-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8e-eKm7o8SdSct3SM8C2zl5aoacz3MnY',
    appId: '1:338772583049:ios:9ce173dbd21303657a1c58',
    messagingSenderId: '338772583049',
    projectId: 'aids-feedback-app',
    storageBucket: 'aids-feedback-app.appspot.com',
    iosBundleId: 'com.example.aidsFeedbackApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRVzBAxZjQ-wmAaWaNH8gQ9P57n5h-sM',
    appId: '1:338772583049:web:55030d796e85c8587a1c58',
    messagingSenderId: '338772583049',
    projectId: 'aids-feedback-app',
    authDomain: 'aids-feedback-app.firebaseapp.com',
    storageBucket: 'aids-feedback-app.appspot.com',
    measurementId: 'G-V6N63ZWGQM',
  );

}